### ISSUE TITLE
Newlines in node labels created weird unicode (?) artifacts

### ISSUE THREAD

**Issue by dnlmc** [ted-marozzi/mermaid-flow-feedback#14]
**Describe the bug**
When entering newlines in node labels (& probably other places), & going back & forth between the code editor, weird unicode (?) artifacts appear in both code editor & UI. First they are normal `\n` then something like `#100` , then eventually super weird `\ﬂ°°110¶ß` as can be seen in [this example](https://www.mermaidflow.app/flowchart#N4IgZgNg9g7iBcoB2UAmBTAzgg2qGAlqgC4AWCATAAwAcANCKegQOanEICMnFDRCICpxoUA7AFYQDAA5RMBYgShIEoAB4IALAGYqAOlEBOEeIriAbKJrjD2hgE8E2nXvOdtho5vGie48ZoAvgyoAIbEoaogAMYQoZiYWLgAugyYxPYQSfA4qSBxAEboEAIAKliKSCwABIRk1aHVSOgwEATNADodgEDfAA293FQAbQD7XX0DnMMjTABO6NUKi9ghBPPRisplAEIgwSAZ0ugC6xFVWQByaMdpGVmq+7Lym0gAggWYUBAArsTHiCANPAdPojCYzJZrLYHE4XG4PF4fH4AoFgvgiGRKLQGExWOwuDw+KgBJYJDRzFIQE8FEoVACgZxzFQYfBnJx9mEIlFYvFEtgcnl0plsrkGIVimUKu0WJTUGt0BtaTs9gxDv8QKdQud0FcMJShfdEI85DTlO9Pj8-lEGUyWWzUXR0SRyPBqPRGMw2Bx4NxeCB+PAQKUAKIAZVK2kp1Je1sojL0ziEtAoOm05hEfsc8FMenEVB03EMFm0AU0nCCIXCkQBPISIsFd3rYtCRRKgZD4cjq1OSvbu32apOCrOLEu131jYeMhNL3NX1+-3UcfMCc0SZEqfTFEzCBzeYLnCL5hLmjLQTRIEIzqx7txXoJfoDQbDpU0UZnvaXwO0ND0FG0ZjiB4hhUDYnCiCyh6GKu5iaKIW7aL4hieByVbcnEdb8qKIAGk2+QthK7Yvm+3bDr2Qb9qq9hHEOGxaqOOrjrcwpTlSH5mh885WvSWg-n+AH+MBoGGOBkHITBcEIUhKGBHk6CoCwIqgIOgbRN86RQAAtpSmmhLMADW6CzKGESzN6IBQEcKgMLpBlGcGSDEoGlnoNZ-pIH8syhIqygAOoYi61DMYaoDpLMUCGf514+vsT7yYpAC0ojeGmxhmKIYj6lA3yzNE6qkuI5KUqZinmUIIgSMVemlQAElqqCGiAnBZTleV1Y5jXNZWXIAuKbYgJSWRVJiMUXipMTqcQWk6XphnGaZ5kuW5tlzQ5TkWVZlLtJ53kvFFI1BThk4AmFEXoPtLrskSAjxegCVTBQNCaPmFC2HBLW5eqHYRlVsylWUxG-bV9WdR9bUg+qXUgJy1agH1AiDa5LAjeyY3UeqakadpNmzUZJl6Ytm043ZsxrQIS1bR5Rm7bSF1YsFi5HeFkUBVwsXrbdSWvaBx7ePmkhpNln0A52QPoOZBVFaq1Xi+1DWQ2D6By6D3Ww-hrYI2KSMo6ieQAG4EC0shmbGrqcHop5UFQwiGOYQjiMImgsimeiGEIaYZTwojJYmDAAF5QNN8D6IYmhMj4sGWIBtvmA60MEKELBeZpACy4uhAAImhAJgOFHkp+EnlRIoxCNRnCdJ6EmnVKUCj3By8o+XSFGyo3ih63h0RaZprnEFheS1nyKSxZgwZqMbxAAApasUADym3wMQszfOgDCjlABShBAwYKegpTo1EqDfFvCBgFviRiu0e8H4GFr8Awt0FyT+80c5RMxF8UCzAIADEBScP-AoFJ9jr03hAXU19X7KRvhqYc9Exx6gYF3aA39Aw-ythgqglJN7RH0knbKjkADCn9UEgB-mAChlDsFfwwLMYhKDf6YKttQ2YtDSikAILg5oCQBB32JHwTAWdMBMCcmfCAiRURAA)

**To Reproduce**
1. Create a node
2. Add text label to it with newlines using Enter key
3. Make edits to code editor & in UI
4. See error -- repeat # 3 & see the cycle of unicode errors develop

**Expected behavior**
Text should reflect actual newlines in both code editor & UI, rather than weird unicode artifacts

**Browser (please complete the following information):**
 - Brave

**Screenshots**
see link above

**Additional context**
N/A

**Comment by ted-marozzi** [comment]
Hey @dnlmc,
Thanks for the detailed issue report and repro steps.
I have pushed a fix out for this, see here:

https://github.com/ted-marozzi/mermaid-flow-feedback/assets/38032037/101ab997-6b4c-430f-beed-4d11d0f3b88c

Thank you for helping improve Mermaid Flow and keep those issues coming!
Cheers.
