### ISSUE TITLE
Add more shapes like square triangle cercle ( if u can).... 

### ISSUE THREAD

**Issue by nareco** [ted-marozzi/mermaid-flow-feedback#15]
**I saw the job that u did on mermaid flow and it is so good I like it from the perspective of a developer** ** I can see the pain and the work that u did** , _but for the user if u wanna make it useful they expect less hand made designing and more pre built shapes tools ... _ 
__**My suggestion are**__ 
- to make more pre made shapes like rectangle square triangle cercle I know the rectangle can be resized but the user needs that at least from my perspective
- **Other thing wanna tell u about** is the responsive design it is little bit un responsive for the phones just take a look on it (phones like Samsung-s10 Huawei...) 

- Add it will be nice feature if u can add WYSIWYG editor when we fill the box so we can format it directly up the keyboard. 
Just like the GitHub editor on the Mobil or the notion editor it will be nice feature . 
Thank u for the great tool again hope u can make something from it and I recommend to add more apps on it like to do list or task manager or kanban app (Trello) because people like to pay for an app that had more options
 if u need interns I am here 😂😆😂😆

Thanks again .

**Comment by ted-marozzi** [comment]
Hi again,

1) Actually Mermaid Flow has quite the variety of shapes on offer as demonstrated by this video. The shapes offered by Mermaid Flow are determined by what is offered by the underlying tool Mermaid JS. See the documentation [here](https://mermaid.js.org/syntax/flowchart.html#node-shapes)

https://github.com/ted-marozzi/mermaid-flow-feedback/assets/38032037/0ad56463-1521-4c13-b96d-0f5d26b5a784

2) Yes this site currently isn't optimised for mobile, when you say unresponsive, do you mean it is slow to load and run, or the content is not usable on mobile? If the later I left some comments about that in #16 

3) A WYSIWYG is a good idea! I will keep that in mind. The primary purpose of the tool is to make generating [Mermaid Diagrams](https://mermaid.js.org/) easier so features outside of that will probably not be pursued unless I see significant product synergy.

I really appreciate you taking the time to give me your thoughts, I am currently not looking for interns, but I will consider it in the future. Thanks again. :)

**Comment by nareco** [comment]
Thanks again for answering. 
No the app is not slow it is good .
Just the responsive design and the positioning of the buttons . 
Thanks 🙏🙏 again wish u the best .

**Comment by ted-marozzi** [comment]
Cheers, closing in favour of #16!
