### ISSUE TITLE
Optimise for Mobile and make design responsive

### ISSUE THREAD

**Issue by nareco** [ted-marozzi/mermaid-flow-feedback#16]
**name of the project is hiding the redo button**
Small issue with the responsive design for the phones , just adjust the project name on the small screens by repositioning it on the left side (left corner ) on making a small menu expend bar that contain the endo redo and reset button .
Also the emport export button is hiding the shapes sections u can add it to the section above and making the workflow more clean and clear to the user . 

![look to the redo button up](https://github.com/ted-marozzi/mermaid-flow-feedback/assets/94112956/503be789-56d8-4b7e-9e30-75a099354fae)

**Comment by ted-marozzi** [comment]
Hi @nareco,
Thanks for raising this helpful issue!
Yes there is a lot of work to be done to make Mermaid Flow usable on mobile. Currently around 91% of Mermaid Flow users use it on desktop, so desktop will be the focus of my efforts until I have made more progress on the editor.
These suggestions are great and will keep them in mind if I get around to improving the mobile experience.

Do you use Mermaid Flow on mobile? If so what for?
Thanks.

**Comment by nareco** [comment]
Hi @ted-marozzi thank u again for the great tool that u made . 
Yeah sometimes i use mermaid flow on mobile devices because mobile is fast on typing and creating shapes . 
for the loading time I think it is good for me it is not slow or something tike that .
