### ISSUE TITLE
Bug: Pasted sub-graph node degrade to ordinary node

### ISSUE THREAD

**Issue by TieWay59** [ted-marozzi/mermaid-flow-feedback#36]
**Describe the bug**

The pasted sub-graph node degrade to an ordinary node

```text
---
title: "Diagram Title"
---
flowchart
	subgraph 811088["0"]
	end
	595704["0-copied"]

%% Mermaid Flow Diagram Link
%% Keep this link to make future edits to your diagram
%% https://www.mermaidflow.app/flowchart#N4IgZgNg9g7iBcoB2UAmBTAzgg2qGAlqgC4AWCAzAAwBMANCKegQOanEI20NEIgAcARkFV+-EAwAOUTAWIEoSBKAAeCAJz8GAT0oAWdQF8GqAIbFTykBFMAjdBD5UJIFBmzwcAXQaZi2iCxcHxAAJ1MkAGtMABFwmCVEYzCIyIRBKVNQ9CRiACVUhCoTeIBlf0CEYlCAV3Rk-0l0Pkwa2xZwyXJfB3QAY2J0VAQwUwhMdCkZOQUkAEFbTCgIGsGrNXhNHX0jEtMWFgIkFhGxieN8IjJKbkZmNg54LnoQXngQAFZ1D4B2Kj0XNJZPJFOsEAYKNt4BQDA1tE0Wm0OqYui4zBYrDZ7I53lQALR9KCSAhDFx+AJBTwhcJRWLxRLAZKSLI5fKFeDFECoMoVZrwap1ZITQIDUnwUbjSYgIEzRQLJYrNaIEAbCFQmG7LnhA5HE7is71EJDFiU7wMABuJJg0lCj1URShnIAXlAoABbdKGZKoAj7cJugCy6AsMXMlmVPuyA1mfAAKgAhFxgUKKYgB8yDUJWeTESrvGK+5FugAEsbklW9BCj8nNppChLdbtZHjNID6NkwExbXmSBEwAFEVDbiAAFCIOADyTUSAqlLGgtjG-dQJtj8L5oFQNTGp0lDAgR3Qa4R7wVvAYxvQ6dCkXQoWPfJARJyLkJ0Cz7wAxLZBD-bAA2EBknnKBFwgAA5NAj3XbMYPeasInndBIIwV9ligD8QE-KgcNwlxFz6SIOigGokFQABhdDMM-MBaLo-CMIwUJKPfPhsNwnCGNCJjY1IAhCKQLAPBAM9hh4WJTEwJhhn1SUvSAA

```

**To Reproduce**
1. Copy&Paste any subgraph node in the editor 

**Expected behavior**

Wish to see a new `subgraph xxx end` node.

**Browser (please complete the following information):**
 - Edge

**Screenshots**
![image](https://github.com/ted-marozzi/mermaid-flow-feedback/assets/40034603/42c080d4-0758-4e68-aeaa-843ed260a300)

**Additional context** 

I came from this discussion, and it seems the HTML bug I met before no longer exists.  https://github.com/orgs/mermaid-js/discussions/4626#discussioncomment-6648434

Anyway, thanks for your product which helps me a lot @ted-marozzi.

**Comment by ted-marozzi** [comment]
Thanks for this detailed bug report, I really appreciate it! I will schedule a fix and update you when its pushed out.

**Comment by ted-marozzi** [comment]
https://github.com/ted-marozzi/mermaid-flow-feedback/assets/38032037/c117a4f0-8352-4808-bd6f-6630fcde9065

Copy and Paste to your hearts intent!
