### ISSUE TITLE
Cannot input text into link with Chinese Input Method 

### ISSUE THREAD

**Issue by editcue** [ted-marozzi/mermaid-flow-feedback#37]
**Describe the bug**
Cannot input text into link with Chinese Input Method , but copy and paste or input English is working
Other component is working .

**To Reproduce**
1. create a link
2. Click on the link
3. input text with any windows Chinese Input Method 
4. nothing input

**Expected behavior**
input text with any windows Chinese Input Method normally

**Browser (please complete the following information):**
 - chrome
 - edge

**Screenshots**
![屏幕采集_20230815_174205.gif](https://s2.loli.net/2023/08/15/DleW2r3qinMNzdg.gif)

**Additional context**

**Comment by ted-marozzi** [comment]
Thanks for raising this issue @editcue, are you able to confirm if it is fixed? I have made some changes to handle edge inputs in a similar manner to nodes.

**Comment by ted-marozzi** [comment]
If its still not working, could you show me how to set up the Chinese input? I am on macOS/chrome.

**Comment by TieWay59** [comment]
![image](https://github.com/ted-marozzi/mermaid-flow-feedback/assets/40034603/11214e97-dced-4e0e-876e-812eaa3995bc)
![image](https://github.com/ted-marozzi/mermaid-flow-feedback/assets/40034603/c01472d4-2f21-4020-87d6-0642d60000c4)

@ted-marozzi it‘s fixed on windows Edge! nice work pal！
