### ISSUE TITLE
Chaining of Linked gets unchained on UI edits.

### ISSUE THREAD

**Issue by ted-marozzi** [ted-marozzi/mermaid-flow-feedback#4]
Issue raised by @dnlmc

A --> B --> C gets compiled to A --- B and B --- A

**Is your feature request related to a problem? Please describe.**
Not sure this ever actually changes the diagram itself, but makes the code more verbose & makes logical pathways less obvious in the code.

**Describe the solution you'd like**
When A --> B --> C get entered into the editor, and the editor is unfocused the formatted code keeps the nodes chained

**Comment by ted-marozzi** [comment]
This one might take a bit of time to come up with a good solution. Currently the compiler is deterministic, in that semantically equivalent diagrams are always compiled to the same code.

I'm not entirely sure if thats a property I want to throw away yet, and if I were to, I think I may want to have implemented a settings system to customise behaviour. If its not too important to you, i'll keep this on the backburner for now until I can come up with a good solution.

**Comment by ted-marozzi** [comment]
Hey @dnlmc this is now fixed at the new editor route: https://www.mermaidflow.app/editor

Not sure if you still use mermaid flow but letting you know :)

**Comment by dnlmc** [comment]
@ted-marozzi awesome, thanks!

I haven't been diagramming lately (been roadtripping most of this year) but when I do I still start with mermaid flow!

new editor looks great!

**Comment by ted-marozzi** [comment]
Legend, enjoy the roadtrip. The new editor should be in super good shape by the time you get back into it
