### ISSUE TITLE
Add 'dark mode' (Light-on-dark color scheme).

### ISSUE THREAD

**Issue by AlexJBSilva** [ted-marozzi/mermaid-flow-feedback#42]
**Is your feature request related to a problem? Please describe.**
Yes. Adding a dark mode will help reduce eye strain on big bright screens.

**Describe the solution you'd like**
Light shapes over a dark background.

**Describe alternatives you've considered**
Didn't think of any alternatives.

**Additional context**
[https://en.wikipedia.org/wiki/Light-on-dark_color_scheme](https://en.wikipedia.org/wiki/Light-on-dark_color_scheme)

**Comment by ted-marozzi** [comment]
Took me a little bit but I am happy to say mermaid flow is now beautiful and contains light and dark modes. You can check out the Mermaid flow 2.0 blog post [here](https://arc.net/l/quote/sdxwffxa)!
If you haven't already I highly recommend playing with the new app.

![image](https://github.com/ted-marozzi/mermaid-flow-feedback/assets/38032037/be3934dc-1aec-46bb-998f-c31f9d8ba03a)
