### ISSUE TITLE
Preserve UI layout on code edits

### ISSUE THREAD

**Issue by ted-marozzi** [ted-marozzi/mermaid-flow-feedback#5]
Issue raised by @dnlmc

**Is your feature request related to a problem? Please describe.**

I can't really use the UI once i start interacting with the code editor (e.g. to organize nodes logically to make them easier to work with, even tho they won't necessarily be rendered this way by Mermaid), because the whole layout gets reset in the UI after each code edit.

**Describe the solution you'd like**
I want to be able to arrange the nodes on the canvas and make code edits without the UI being reset.

**Comment by ted-marozzi** [comment]
Experimental support for this shipped. Anyone has feedback, drop it here!

**Comment by dnlmc** [comment]
@ted-marozzi just played around a bit & seems to be working !

**Comment by ted-marozzi** [comment]
Cool, closing as completed for now :)
