### ISSUE TITLE
Please consider subgraphs

### ISSUE THREAD

**Issue by bish0polis** [ted-marozzi/mermaid-flow-feedback#8]
**Is your feature request related to a problem? Please describe.**

For grouping *everything* I use subgraphs.  When mermaid supports shapes made of arbitrary tables with node points embedded, I'll gleefully use that, but for now I still just gather some nodes into a subgraph to represent, like, ports on a switch.

I'd love to continue abusing the subgraph workflow in flowcharts in mermaid-flow

**Describe the solution you'd like**
a box-like construct should be able to receive node objects created and/or dragged into the container box, and suffer links into and out of the nodes inside and to the container itself; which also can accept labels and orientations and fill colours and line colours, and, and, and, etc.

**Describe alternatives you've considered**
I haven't considered any; I'm sorry.  I leave my nodes an ad-hoc mess in mermaidFlow the same as I leave objects on my cluttered desk like so many homeless little sleeping gnomes... gnomeless? .. and look at them in increasing guilt and despair.

**Additional context**
None to add here.  Sorry.  I may have come woefully unprepared.  Guilt and despair is increasing.

**Comment by ted-marozzi** [comment]
Haha thanks for the laugh. Agreed, I have done the logic work to support this idea, I just need to create a front end for it. I will bump it up the priority list.

**Comment by ted-marozzi** [comment]
Hey, been working on this. Quite a lot of edge cases so it will take some time to polish up. There are bugs but the basic usecase should work. [Try it out this alpha feature here](https://mermaid-flow-git-subgraphs-ted-marozzi.vercel.app/flowchart#N4IgZgNg9g7iBcoB2UAmBTAzgg2qGAlqgC4AWCALAIwUA0Ip6BA5qcQgMwcAM9RCIAGzUArCIDsIegAcomAsQJQkCUAA9KAJg70AnggAc3AL71UAQ2LnVICOYBG6CAKpSQKDNng4Q4kR3EAkABdegAncyQAa0wAEQiYFURTEAjohCoZczD0JGIAJUiohF4QVASAZWJdCHQEYjCAV3QU6uk6+BBMRvtmCOlyGTkFJSQAQXtMKAhG4g71LR0QfXgjFMwndABjOdQEMHMIDbMI5mYCJGZ9w+Ou6tqbQhJyeGo6BiZWdnguE3CsAgALwuV3gByOLVo+CIZAQmm4BnojBYbAyVE0fD2nT8ASCQ3kimUNg08BoggAdJpBBwKBQ-HTxEZuII9IYOJSRAZBCIKBxOdwEdwKCkLFYbHZHM5OgAhczyLZuNIxeLmRKqFLSbK5ApFDInVVVGodBrNVq6doCHI7SLMWoAOTQdXxI2UEymMzmxIQIkEAE5KdTafTxIzuJllhlqRyuTy+UyjMKsjk8g6MAJhFQxJJ6Btajt0FjwbdyuYziDrhDTNDnpwuUjPqifjxMQJfb70YJsyBZATRl74FTxKz4OIqH8ypZrIhbA4nAIOG4PFhcCARMzfbSQuEinEEklgCklXru1q8oV0vBSiWYIaHvATZCQG0Ol0en1zAM3LntrsK7cey64yTNMszzCAJKDsOo7jiWZaXH+kLVrCA4IvWKLfFQ6Itp0a5+puzqEvu4EIOILIRqS8IipO4qzlKIAVI00iyGE7DbtEu6qvuGqnjqF7htet7Gk0j7PpaP42vajpuABhFuiBnrTiSNJLCsBg8NxybEKmL5th2XbfvmhY3Og+pwaCRaISATzIdQGIfOhnDNiA-A4ZmgjUtJwyEf2AC0mgiJo5IhiIvrUtw4gUNwmjUGRKzogYHKdmGIV8tQHBUWK04SnOOGLo6Xg+L6NIiFQBhuLSwjMluqQ7iqarJGxxSkkm2rnk1V6VPcQnNPQBbMMu3igKJnRbI0mDEFAAC2biTdkUToGEVTZN8IBQO0Kj0LNYTzWEACiSBYqt61uBccwRDsowAOowi88I5l1NjjWEUDzddNakusUCNGEWwvhVkWCF+X0-egAASkSoHeICaG4VhhP1K1FRQJVlfQcMI+DB1Q642EgH16A+TSY5csIfKYW4kQELNv5gsZ9CAgAkgd6AkqUBk0xZxjBGaFqdN0vT9IMXSbIZCEEaMckemBJJ+QFQV+KFPARVFMXDvFiXiMlRU8lQ6Wmec8G0xC91Go8N2UFh9lfI5445PIwKG5zUJWebKGIlbjaYXZLkgEjKOeb2RKKSRCXhcrY48L6WbvHF4j+hHBgBZooXcKFPoZVOoDZXRMONRx9UHi1Z66s1ZSdab97CTzL5WlYlySWm4uusBUu+VQEXkn6ieCPCvLMgYFB2SsSvkhwgjcGIHAGAYiuMoIGnatpAglT6Hk5iLHN02XpYG+ZxlVi773wu7yLW6Sls+-9VVN0RJKYeIQXMuImgGPCbYhX4w4UAlkVUO2z8KwRBFRME5MpZ1oi4RUtU9zqiLrxJq-Fy53gfNXMS1p67oCXuvPMm9jbdi8hLFuoE258nJOubQ39KrCBjhkUindOSCFKlyDca4hQilOLvMWJ5NJL1cqvBcXNeqoH6gVIa5oXyjXGlNGac0FpLRYgINauQZHbQWvtQ6SiNrOTyAtcwF1lBvWQndO4FdQBPReugQxLwqCfW+r9AQOJAj6WBr9TGkMXy5yfNkBGrZ2yDlht49AxA3HYxOodfGPkQphhxGPCgPcKZICppYAsXDGbM1Ztgn8KSjYbAPsNEAkiJrTU2rIxacMVqaJUTtdRijjp8B0edQiVi4RswetOcxr1XY2JzC4l8GYsxAzsWDCGUNPHoyCb4vSAT4ZBJCS+HGzlwnCIJj6eEEhNZR0igkpJuDbhpIwBk4WODskWTMNRLKEDOgMQFh+IWBBMC7VQCMR2+88niIEIU6RJTVFlOWrU5R3zqkHX+Vo06uj9FIGaShE2d4zENAsVC7pXRekCCvoDHpQy5kCDGYExGxVSrTIxiM+ZYSBARKJgidyvISoLMptTE5W99ksxKJk0WOSWihBAAANwIOgGAzFvgLAHJoKg5IRDDhFeycVIBARQGkZeMVxgRQEFLBESaABZIJ5hYjnNAE82ufZOgABVpRuDAM9PI6rLBnRsIoYgUNYgqvfJNAABEahQDxlUGq5QNHAnKthTUmtqAq-q7CYA2CGpVQA) and report any bugs. Once its stable i'll deploy to production.

**Comment by ted-marozzi** [comment]
I have merged this to production, I'll leave this open for some time for feedback. Thanks.

**Comment by bish0polis** [comment]
I can confirm I can now police up all my wandering nodes into their proper groupings and at least limit their entropic sprawl.  Node liberty be damned, OCD wins the day.  Very excellent; and sorry for apparently ghosting for a week.

**Comment by dnlmc** [comment]
Dropping in to confirm that I just loaded up a graph to make some updates & subgraphs seem to work great on initial load!

But when I make an edit via the code editor, the UI Subgraphs shrink & can no longer tell which nodes are supposed to be in them -- but they do stay "grouped" with the subgraph & will follow drag & drops of the subgraph. 

This is a minor issue, but dropping it here FYI, & also to say its great to see development continue here!

**Comment by ted-marozzi** [comment]
Hey thanks, do you have a graph I can reproduced this issue with?

**Comment by dnlmc** [comment]
@ted-marozzi if you paste this one in it works at first, but if you edit the code, the UI render of the subgraph boundaries get weird.

then you have to copy the code, hit "clear" & re-paste it to get it to render right 

```flowchart
	subgraph one
		a1 --> a2
	end
	subgraph two
		b1 --> b2
	end
	subgraph three
		c1 --> c2
	end
```

**Comment by ted-marozzi** [comment]
Huh you are right, thats a weird one. Thank you!

**Comment by dnlmc** [comment]
@ted-marozzi thanks, working now!  

I did notice one other minor bug, which is if you use the same initial graph above, then try to add a new node INSIDE a subgraph, it will be kicked outside of the subgraph (& UI) on render

I can sometimes get it to work by playing with both the UI and code editor, but seems impossible to get it to stay just via editor edits

**Comment by ted-marozzi** [comment]
Yeah, I noticed this too and will look into it! :)

**Comment by ted-marozzi** [comment]
Hey @dnlmc,

This issue should be fixed now as per the video, I'll close this issue for now but please reopen another issue if you hit an problems.

Also, I just upgraded the layout engine to the more powerful elk js to support some more powerful layouts, so the layout won't as closely match the mermaid js image layout (until they finish their elk renderer implementation) and things aren't as centered and aligned (something I should be able to fix but just haven't yet). Any feedback is welcome!

https://user-images.githubusercontent.com/38032037/230860528-a2ec2fc7-32e6-4c10-8a28-4e4d928bac12.mov
